# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: Proofs

on:
  push:
    branches:
      - stats-test

jobs:
  mcs:
    name: MCS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [RISCV64]
    steps:
    - name: Proofs
      uses: seL4/ci-actions/aws-proofs@stats
      with:
        L4V_ARCH: ${{ matrix.arch }}
        isa_branch: ts-2019
        manifest: mcs.xml
        session: ASpec
        cache_write: ''
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SSH: ${{ secrets.AWS_SSH }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
